#server:
#port: 8083
#spring:
#datasource:
#  driverClassName: com.mysql.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/salaodebeleza
 # username: root
 # password: root
#jpa:
 # hibernate.ddl-auto: update
 # generate-ddl: true
 # show-sql: true

server:
port: 8083
spring:
datasource:
  url: jdbc:h2:file:C:/Cursos/MBA/Spring/spring_back_end/salaodebeleza;DB_CLOSE_ON_EXIT=FALSE
  username: root
  password: root
  mvc:
  pathmatch:
      matching-strategy: ant_path_matcher
jpa:
 hibernate.ddl-auto: update
 generate-ddl: true
 show-sql: true
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
queue:
  order:
    name: OrderQueue
